---
title: "Explora ruido madrid"
output: html_notebook
---

TODO:
- promediar mensualmente LeqT para todos los años y comparar con 2020.
- Estaría bien crear una semana tipo promediada para todos los años que tenemos datos. En este caso habría que tener cuidado en promediar lunes-lunes, martes-martes...

```{r}
library(dplyr)
library(reshape2)
library(magrittr)
library(lattice)
library(latticeExtra)
library(zoo)
```

```{r}
data <- read.csv("data/datos_ruido_madrid.csv", sep=";", strip.white = TRUE)
colnames(data) <- c("Station","Year","Month","Day","Period","LAeq","LAS01","LAS10","LAS50","LAS90","LAS99")

data$Date <- as.Date(with(data, paste(Year, Month, Day, 
                                      sep="-")), "%Y-%m-%d")
data <- data[order(data$Date),]

head(data)
```

# muestra de datos diarios de una estación Leq

```{r}
xyplot(LAeq~Date|as.factor(Station[1]), groups=Period, data=data[data$Period == "T",], type='l',strip = FALSE)
```

Media mensual de todos los años excepto 2020


```{r}
data %>%
  filter(Year != 2020) %>%
  group_by(Month) %>%
  summarise(mean_LAeq = mean(LAeq),
            mean_LAS01 = mean(LAS01),
            mean_LAS10 = mean(LAS10),
            mean_LAS50 = mean(LAS50),
            mean_LAS90 = mean(LAS90),
            mean_LAS99 = mean(LAS99)) 
```


Año 2020
```{r}
data %>% 
  filter(Year == 2020) %>%
  filter(Period == "T") %>%
  group_by(Month) %>%
  summarise(mean_LAeq = mean(LAeq),
            mean_LAS01 = mean(LAS01),
            mean_LAS10 = mean(LAS10),
            mean_LAS50 = mean(LAS50),
            mean_LAS90 = mean(LAS90),
            mean_LAS99 = mean(LAS99)) 
  
```


